export const siteConfig = {
  name: 'Jossue Sarango',
  title: 'Jossue Sarango — Mechanical Design Engineer',
  description:
    'Jossue Sarango is a Mechanical Engineering student at NJIT designing physical mechanisms for hardware, from CAD and tolerance stack-ups to a shipped autonomous robot deployed in the field. Explore projects, experience, research, and more.',
  url: 'https://jossue.dev',
  author: 'Jossue Sarango',
  twitterHandle: '@JossueAI',
  keywords: [
    'Jossue Sarango',
    'mechanical design engineer',
    'mechanical engineer',
    'NJIT',
    'CAD',
    'SolidWorks',
    'GD&T',
    'FEA',
    'tolerance stack-up',
    'robotics',
    'portfolio',
    'React',
    'Next.js',
    'TypeScript',
  ],
};
