/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 accord.glb --transform 
Files: accord.glb [1.96MB] > /home/jossue/dev/portfolio/public/models/accord-transformed.glb [1.3MB] (33%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/accord-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CHASSIS_chass_0.geometry}
        material={materials.PaletteMaterial001}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.CHROME1_CHROME_0.geometry}
        material={materials.PaletteMaterial002}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.F_LIGHT_phong8_0.geometry}
        material={materials.PaletteMaterial003}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <group position={[8.009, 2.392, -2.262]} rotation={[3.142, 1.566, -3.142]} scale={0.134}>
        <mesh geometry={nodes.glass1_glass_0_1.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.glass1_glass_0_2.geometry} material={materials.PaletteMaterial005} />
      </group>
      <mesh
        geometry={nodes.GLASS_B_int_glass_0.geometry}
        material={materials.PaletteMaterial006}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.GLASS_RED_red_glass_0.geometry}
        material={materials.PaletteMaterial004}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Honda_Accord_2021_shell001_Mesh_104_BKACK_GL_0.geometry}
        material={materials.PaletteMaterial007}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Honda_Accord_2021face_39_INSTALOD_14_Mesh_19_phong19_0.geometry}
        material={materials.PaletteMaterial008}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={
          nodes.Honda_Accord_2021shell_0_08_03_dupl1_INSTALOD1_Mesh_111_002_rear_light_0.geometry
        }
        material={materials.PaletteMaterial009}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Honda_Accord_2021shell_0_10_14_INSTALOD_Mesh_044_ext_0.geometry}
        material={materials.PaletteMaterial010}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={
          nodes.Honda_Accord_2021shell_0_dupl2_INSTALOD_INSTALOD_2_Mesh_48_001_standardSurface1_0
            .geometry
        }
        material={materials.PaletteMaterial011}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.MIRRORS_mirror_Mat_0.geometry}
        material={materials.PaletteMaterial012}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.paint1_paint_0.geometry}
        material={materials.PaletteMaterial013}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Honda_Accord_2021asdasfdf_Mesh_5_004_plas_black_0.geometry}
        material={materials.PaletteMaterial014}
        position={[8.009, 2.392, -2.262]}
        rotation={[3.142, 1.566, -3.142]}
        scale={0.134}
      />
      <group position={[3.245, 1.322, 6.242]} rotation={[-1.592, 1.331, 1.592]} scale={0.141}>
        <mesh
          geometry={
            nodes.Honda_Accord_2021polySurface3648_Mesh_2_005_Honda_Accord_2021RIM_0001_1.geometry
          }
          material={materials['Honda_Accord_2021RIM.001']}
        />
        <mesh
          geometry={
            nodes.Honda_Accord_2021polySurface3648_Mesh_2_005_Honda_Accord_2021RIM_0001_2.geometry
          }
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={
            nodes.Honda_Accord_2021polySurface3648_Mesh_2_005_Honda_Accord_2021RIM_0001_3.geometry
          }
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={
            nodes.Honda_Accord_2021polySurface3648_Mesh_2_005_Honda_Accord_2021RIM_0001_4.geometry
          }
          material={materials['Material.005']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/accord-transformed.glb');
