/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desk.glb --transform 
Files: desk.glb [43.8MB] > /home/jossue/dev/portfolio/public/models/desk-transformed.glb [3.48MB] (92%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/desk-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.M_7bf6472fea097980a562bf7f4fb70606}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_109.geometry}
        material={materials.M_31c46228d9fc209da0cb6bdfcb9dd2518}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.M_7125986aec9d2f8ff2ea6731de9eeb66}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_111.geometry}
        material={materials.HUD_S_07}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials.f0de716bbfdaa7d8a043aa6d2d4ab4d2}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.vlcsnap_2015_07_02_20h01m05s60}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_117.geometry}
        material={materials.M_40d183417e8bc01d30b3d39b15a83227}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials.HUD_S_08}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_119.geometry}
        material={materials.M_1ddf496e3e17fe5440b176e91dcfcfef}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials.HUD_S_03}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_121.geometry}
        material={materials.M_54d6446cfe1f3f00dee3eade539dafae}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_122.geometry}
        material={materials.material_80}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_126.geometry}
        material={materials.PaletteMaterial002}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_133.geometry}
        material={materials._Chipboard_4}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials.Project1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials.oordop}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_139.geometry}
        material={materials._CorrogateShiny_1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.c4cfcc9434a058f775c9beddc0589caf}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.Aluminum}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.AM134_27_vinyl_red}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.material_35}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.AM134_27_vinyl_black}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials.material_43}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.main_plastic_dark}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_95.geometry}
        material={materials.main_plastic_grey}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.hand_written2}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.194}
      />
    </group>
  );
}

useGLTF.preload('/desk-transformed.glb');
