/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/garage-transformed.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/garage-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group position={[-1.763, 2.678, -3.997]} rotation={[Math.PI / 2, 0, 0]} scale={0.012}>
        <mesh geometry={nodes.Chandelier001.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Chandelier001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group
        position={[3.765, 1.594, -5.91]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={1.171}
      >
        <mesh geometry={nodes.Light_tube005.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Light_tube005_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh
        geometry={nodes.Light_tube006.geometry}
        material={materials.PaletteMaterial005}
        position={[-5.798, 3.018, -0.78]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.107, 1.171, 1.171]}
      />
      <mesh
        geometry={nodes.Light_tube014.geometry}
        material={materials.PaletteMaterial006}
        position={[2.969, 3.75, 3.1]}
        rotation={[0, 1.571, 0]}
        scale={[1.756, 1.171, 1.171]}
      />
      <mesh
        geometry={nodes.Scene_structure_001.geometry}
        material={materials.PaletteMaterial007}
        position={[0, 0, -0.05]}
      />
      <mesh
        geometry={nodes.Scene_structure_048.geometry}
        material={materials['Scene setting_097']}
        position={[0, 3.7, -2]}
      />
      <mesh
        geometry={nodes.Scene_setting_039.geometry}
        material={materials['Scene setting_113']}
        position={[4.412, 1.02, 0.443]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Scene_setting_085.geometry}
        material={materials['Scene setting_225']}
        position={[0, 3.575, -5.74]}
      />
      <group position={[-1.647, 1.119, -5.791]} scale={0.861}>
        <mesh
          geometry={nodes.Scene_setting_089_1.geometry}
          material={materials['Scene setting_201']}
        />
        <mesh
          geometry={nodes.Scene_setting_089_2.geometry}
          material={materials['Scene setting_205']}
        />
      </group>
      <group position={[-1.778, 1.389, -5.843]} rotation={[-Math.PI, 0.162, -Math.PI]}>
        <mesh
          geometry={nodes.Scene_setting_090_1.geometry}
          material={materials['Scene setting_219']}
        />
        <mesh
          geometry={nodes.Scene_setting_090_2.geometry}
          material={materials['Scene setting_229']}
        />
        <mesh
          geometry={nodes.Scene_setting_090_3.geometry}
          material={materials['Scene setting_230']}
        />
        <mesh
          geometry={nodes.Scene_setting_090_4.geometry}
          material={materials['Scene setting_231']}
        />
      </group>
      <mesh
        geometry={nodes.Scene_setting_091.geometry}
        material={materials['Scene setting_228']}
        position={[-3.608, 0.772, 1.593]}
        rotation={[-Math.PI, 0.035, -Math.PI]}
      />
      <mesh
        geometry={nodes.Tools_001.geometry}
        material={materials.PaletteMaterial007}
        position={[-0.025, 1.254, -5.973]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.boolean_cutters_003.geometry}
        material={nodes.boolean_cutters_003.material}
        position={[-6.638, 2.538, -5.833]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.346}
      />
      <mesh
        geometry={nodes.Scene_setting_011.geometry}
        material={materials['Scene setting.006']}
        position={[2.778, 1.051, -5.657]}
      />
      <group position={[1.826, 1.458, -5.871]}>
        <mesh
          geometry={nodes.Scene_setting_013_1.geometry}
          material={materials['Scene setting.008']}
        />
        <mesh
          geometry={nodes.Scene_setting_013_2.geometry}
          material={materials.PaletteMaterial008}
        />
      </group>
      <group position={[4.347, 1.36, -2.049]} scale={1.2}>
        <mesh
          geometry={nodes.Scene_setting_019_1.geometry}
          material={materials.PaletteMaterial009}
        />
        <mesh
          geometry={nodes.Scene_setting_019_2.geometry}
          material={materials['Scene setting_075']}
        />
      </group>
      <mesh
        geometry={nodes.Scene_setting_020.geometry}
        material={materials['Scene setting_098']}
        position={[4.359, 1.087, -0.456]}
      />
      <mesh
        geometry={nodes.Scene_setting_024.geometry}
        material={materials['Scene setting_014']}
        position={[4.381, 1.808, -0.165]}
        rotation={[0, 0.468, 0]}
        scale={1.2}
      />
      <mesh
        geometry={nodes.Scene_setting_027.geometry}
        material={materials['Scene setting_004']}
        position={[4.367, 2.243, -0.709]}
        scale={1.2}
      />
      <group position={[-6.008, 1.129, -5.793]} rotation={[Math.PI, -1.206, Math.PI]}>
        <mesh
          geometry={nodes.Scene_setting_040_1.geometry}
          material={materials['Scene setting_115']}
        />
        <mesh
          geometry={nodes.Scene_setting_040_2.geometry}
          material={materials['Scene setting_116']}
        />
      </group>
      <mesh
        geometry={nodes.Scene_setting_054.geometry}
        material={materials['Scene setting_122']}
        position={[0.091, 0.994, -5.4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Scene_setting_055.geometry}
        material={materials['Scene setting_123']}
        position={[0.53, 0.927, -5.685]}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload('/garage-transformed.glb');
