export { aboutData } from './about';
export type { AboutData, Highlight, SkillGroup } from './about';
export { contactLinks } from './contact';
export type { ContactLink } from './contact';
export { experienceData } from './experience';
export type { ExperienceEntry } from './experience';
export { projects } from './projects';
export type { Project } from './projects';
export { researchData } from './research';
export type { ResearchEntry } from './research';
