export interface ResearchEntry {
  id: string;
  title: string;
  heroImage?: string;
  /** Body text in markdown format */
  body: string;
}

export const researchData: ResearchEntry[] = [
  {
    id: 'future-of-flight',
    title: 'The Future of Flight',
    heroImage: '/research/hybrid-air/plane-diagram.jpeg',
    body: `# The Future of Flight
**By Jossue Sarango**

## Are Electric Planes the Future?
In a revolutionary world that discovers, evolves, and changes day by day, people often learn that their favorite activities might not be so great after all. A study discovered that in 2023 alone, approximately 4.4 billion passengers traveled via airlines worldwide, an estimated 1.8 billion were international travelers, and 2.6 billion were domestic (Hyde 2024). Only a small fraction of that amount understood just how carbon-intensive flights truly are. To put that into perspective, researchers calculated planet Earth inhabits roughly 8.2 billion people, of which 33.2% are not even of legal age to fly alone (Ang 2021).

Aircraft, either for leisure or for business, shape the world as we know it. Your Amazon package, your mail, and your medications are all forms of air cargo that rely on domestic air travel to get from one destination to another. Airplanes act as a portal to connect countries worldwide and allow families to connect without boundaries. Famous airlines such as United, American Airlines, and Delta fly in and out of the 20,000 airports inside the US. These multi-million corporations have demonstrated resilience against global pandemics and continue to profit from a growing consumer audience that enjoys traveling the world. At a glance, airplanes are a revolutionary invention that are perfect for connecting lands and transporting goods. The truth is, with every plane that goes into the sky, toxic fumes and gases are let into the Earth's atmosphere.

## Global Warming
A recent study discovered that the United States alone accounts for 200 million tons of the global CO2 total, approximately 23%. That same study estimated aviation's contribution at 2.5% of global CO2 emissions, a number that might seem like a small fraction, but its impact is disproportionately large and growing rapidly (Overton 2022). While the common misconception that planes dump toilet waste during flights is undoubtedly false, planes do indeed produce a different kind of waste: carbon waste. This waste is not only harmful due to the sheer volume of emissions, but also specifically where they are released.

Aircraft, relative to other forms of travel, fly high in the Earth's atmosphere, effectively capturing heat and trapping exhaust fumes that are constantly released during flight. Through global warming, the impact of CO2 emissions is already being felt throughout the globe. The USEPA found, "scientific studies indicate that extreme weather events such as heat waves and large storms are likely to become more frequent or more intense with human-induced climate change" (USEPA 2025). The stability of our societies and economies is nevertheless threatened by these gases, driving moral character to question what can be done?

Despite commercial airlines being driven by profit and finding areas to cut corners with the goal of increasing revenue, growing awareness has driven airlines to cut back on their minimalist spending habits to identify solutions to existing emissions. A solution identified by researchers and made popular by media outlets is hybrid technology.

## How does Hybrid-Technology Work?
Hybrid-electric aircraft work differently from traditional aircraft. Rather than relying solely on combustion engines, which burn fuels and release toxic fumes as a by-product, hybrid technology incorporates electric motors to reduce the reliance on traditional engines. In essence, aircraft will stop depending solely on combustion engines and rely on electricity to power all non-essential systems and produce thrust. Some popular electric commodities popular to consumers are Wi-Fi, reading lights, and movies on infotainment screens.

From an operational standpoint, electrifying systems means relying on batteries to power radio communications, power steering, and cruise control. Yet the integration of batteries does not stop there. What truly makes hybrid technology unique is its ability to allow batteries and engines to work seamlessly together. This synergistic interaction encompasses electric motors operating in parallel to internal combustion engines within an aircraft to produce augmented power that is both effective and reliable.

To the ordinary traveler, this translates to a quieter cabin experience throughout the entire flight, faster connection speeds, and a better self-appreciation for flying green. Research already suggests that engaging in environmentally friendly practices directly impacts one's happiness (Amori 2025).

## Will Airlines Adopt This Technology?
For decades, the aviation industry has steered away from the idea of introducing cleaner energy practices, labeling them as costly, complex, and frankly unnecessary. Despite this, public demand, fueled by increasing awareness, has demanded changes to be made in an industry that directly contributes to greenhouse gases.

In 2022, the electric aircraft market was estimated to be about $8.8 billion, with an estimated reach of roughly $37.2 billion by 2030 (Mehra 2022). Scientists have raised their voices to promote a safer alternative that still allows airlines to maintain profit margins and reduce their carbon footprint. Driven by aircraft manufacturers, an analysis on the correlation between hybrid-electric aircraft and aircraft pollution discovered that the adaptation would allow the United States to reduce greenhouse gases and petroleum consumption by 80% by the year 2050 (Zhang 2024).

The aviation industry can no longer afford to ignore its contribution to the existing global warming problem. European countries like Austria, Belgium, and the Netherlands have already been victims of airline regulations to reduce toxic fumes released into the atmosphere. France is another example, where the country's national assembly has made the decision to fully ban short-haul flights that could otherwise be traveled through other methods of transportation.

The concept behind this decision is true: regional short-distance flights are both inconvenient and environmentally damaging. A typical road trip from John F. Kennedy Intl. (JFK) to Atlantic City Intl. (ACY) is roughly 2 hours and 20 minutes, while a flight traveling those same distances takes 45 minutes. Though flying might seem like the faster and more efficient alternative at first glance, it fails to account for the time required to pass through security, bag check-in, and waiting for other passengers to board the flight. Combined, commuting on an electric land vehicle and traveling on a carbon-intensive aircraft take roughly the same time to reach the destination, while the difference in carbon emissions is exponentially large.

## Impact of Hybrid Technology on Communities
The introduction of hybrid-electric allows aircraft to travel more efficiently domestically, introducing it as a new viable method of transportation and directly increasing regional funding. Washington State's Department of Transportation conducted a study that identified hybrid-electric aircraft as an opportunity to repurpose neglected local airports and increase local tourism (WSDOT 2020). Shifting towards cleaner skies successfully promotes the usage of airplanes to travel regionally, a modern form of transportation that is faster and more efficient.

For airline companies, this shift expands their reach to an audience they once never factored. An American startup company, Ampaire, has recently made headlines due to its bold claims that its new hybrid-electric propulsion technology successfully lowers fuel consumption by 90%, aircraft maintenance by 50%, and noise pollution by 60% (Ampaire 2025). They highlight the benefits of regenerative braking, a hybrid-technology characteristic that allows batteries to charge as the aircraft is braking or descending. The convenience of this is that hybrid-electric aircraft can continue to travel distances without taking extensive breaks to charge their systems.

## Why is This Important?
The introduction of hybrid-electric aircraft challenges transportation as we know it to change and adapt to the needs of the world. Urban cities will continue to expand as human population numbers reach an all-time high. A study analyzing urban infrastructure identified that current transportation infrastructures are inflexible and stationary, forcing traffic to experience jams and congestion (Beebe 2018). The proposed solution is the introduction of an air taxi system that can shift according to the needs of the city's infrastructure. Nevertheless, hybrid technology opens the possibility for multiple discoveries that are sure to change our concept of transportation.

## When Will This Happen?
Despite being a newly introduced technology, many airlines have begun to implement testing prototypes and identify methods of mainstreaming hybrid-electric aircraft. Companies like Heart Aerospace and Pipistrel are already leading the way in developing innovative aircraft like the ES-19 and the Alpha Electro.

Having already received the European Union Aviation Safety Agency certification, the Alpha Electro operates using a 60-kW motor and a 21-kWh battery. Combined, the motor and battery allow the Alpha Electro to travel for nearly 160 kilometers, a flight duration of exactly one hour (Walków 2019). United Airlines has recently publicly announced its shift towards air freight carriers to allow for enhanced mobility in densely populated areas (United 2021).

The shift towards electrified skies is happening sooner than we know it, slowly but surely incorporating into the existing fleet of over 200 thousand aircraft (Schwab 2021). As prototypes and different designs continue to be crafted and released publicly, it is exciting to view the future happening before our eyes. These new aircraft represent a modern era of air travel, one that is cleaner, quieter, and environmentally conscious.

---

## References

* **Amori, M.** (2025, April 25). Could going green make you happier?. SPSP. https://spsp.org/news/character-and-context-blog/prinzing-living-sustainably-promotes-happiness-well-being
* **Ampaire.** (2025). Clear skies ahead: Our electric-hybrid system takes flight. https://www.ampaire.com/
* **Beebe, A. J. B.** (2018). "Electric Flight Will Transform Our Cities for the Better, and It Will Happen Sooner Than You Think."
* **Hyde, D.** (2024). Aviation: Benefits beyond borders global report. https://aviationbenefits.org/downloads/aviation-benefits-beyond-borders-2020/
* **Mehra, A.** (2022). Electric Aircraft Industry. Market Research Firm. https://www.marketsandmarkets.com/PressReleases/electric-aircraft.asp
* **Overton, J.** (2022). Issue brief: The growth in greenhouse gas emissions from Commercial Aviation EESI. https://www.eesi.org/papers/view/fact-sheet-the-growth-in-greenhouse-gas-emissions-from-commercial-aviation
* **Schwab, A.** (2021). Electrification of Aircraft: Challenges, Barriers, and Potential Impacts. National Renewable Energy Laboratory (NREL). https://www.nrel.gov/docs/fy22osti/80220.pdf
* **United.** (2021). "United Adding Supersonic Speeds with New Agreement to Buy Aircraft from Boom Supersonic." United. June 3, 2021. https://hub.united.com/2021-06-03-united-adding-supersonic-speeds-with-new-agreement-to-buy-aircraft-from-boom-supersonic-2653216403.html
* **USEPA.** (2025, March 25). Climate Change Indicators: Weather and Climate. https://www.epa.gov/climate-indicators/weather-climate
* **Walków, Marcin, and Qayyah Moynihan.** (2019). "This Electric Plane Takes Just One Hour to Charge and Can Travel 160 Kilometers for Just $5." Business Insider (June 19, 2019). https://www.businessinsider.com/electric-plane-charges-in-hour-can-cover-160km-2019-6/.
* **WSDOT.** (2020). Electric Aircraft Working Group Report. June 2019. WSDOT Aviation Division. https://wsdot.wa.gov/sites/default/files/2019/07/15/ElectricAircraftWorkingGroupReportJune2019.pdf
* **Zhang, Hans & Harris, Joy.** (2024). Exploring the Technology Needed to Build Electric Passenger Planes. Journal of Student Research. 13. 10.47611/jsrhs.v13i1.6196.`,
  },
  {
    id: 'hybrid-air-white-paper',
    title: 'Integration of Electric Aircraft Systems',
    heroImage: '/research/hybrid-air/comparisson-table.jpeg',
    body: `# A White Paper on the Integration of Electric Aircraft Systems
**By Jossue Sarango**

## Executive Summary
Electric aircraft propose the opportunity for reduced environmental damage while expanding the reach of local communities. This white paper analyzes the feasibility of their implementation and identifies challenges with integrating hybrid technology.

In response to the beginning production of small electric aircraft, traveling short distances with minimal passengers, airline corporations have begun searching for opportunities to commercialize this technology. Approximately 170 different electric aircraft are already underway internationally, a growth of over 50% compared to previous years (Selkirk 2020). The introduction of new technology creates room for growth in a very competitive and profitable market. Driving forces to adopt this technology include:

* **Lower Costs:** Electric planes promise savings in the areas of fuel and maintenance, lowering the overall price of travel for companies and their passengers.
* **Cleaner Flight:** Electric planes reduce nitrogen oxide emissions by 95% (Chu 2021). Electric motors also produce significantly less noise than traditional combustion engines and reduce noise pollution.
* **Regional Travel:** Electrified air travel introduces a new method of urban transportation that reduces congestion and connects regional airports.

This paper examines the potential benefits of adopting this technology, how it functions, and weighs the challenges that limit the expansion of electric aircraft commercially.

## Introduction
Aviation, representing one of the world's leading forms of transportation, both for leisure and for business, is simultaneously one of the most carbon-intensive forms of travel. The United States alone accounts for 200 million tons of the global CO2 total, approximately 23% (Overton 2022). Combined, aircraft are responsible for 5% of the world's global warming, gradually increasing the Earth's surface temperature, threatening food security, human health, and ecosystems. The demand for air travel is now higher than ever; in 2023 alone, approximately 4.4 billion passengers traveled via airlines, an estimated 1.8 billion were international travelers and 2.6 billion were domestic (Hyde 2024).

Though the release of toxic gases into the atmosphere has remained the same for decades, airline companies have begun making attempts to reduce their carbon footprint in response to media backlash. Modern strategies to achieve carbon neutrality by 2050, have driven companies to strive for operational efficiency: increasing seating capacity per aircraft and fitting as many passengers as possible without exceeding capacity (Ingram 2023).

Though these efforts point in the right direction, their opportunity for growth and improvement is extremely limited, especially in the plummeting regional travel market. The notion of dumping millions of toxic fumes into the atmosphere for a distance that could similarly be traveled through land rails makes near-travel flights futile. This inefficiency combined with the cost per passenger, fuel, maintenance, and staff, steer airlines from hosting regional flights.

The introduction of aircraft electrification, rather, aligns with reduced cost promises, environmental benefits, and introduces near-distance flights as a viable option for travelers. Historically, in the face of financial burdens, airlines have customarily retired less efficient planes to replace them with more viable aircraft that maximize efficiency. This shift creates the opportunity to explore different propulsion technologies, such as hybrid-electric aircraft that integrate electric motors to reduce carbon footprint and noise pollution. Though small electric planes are beginning to make breakthroughs and integrate with regional travel, to achieve this nationally, there must be improvements to how airports and power grids adapt.

> **Figure 1. Operating Hybrid Electric Aircrafts in the National Airspace System**
> *Source: NASA Technical Reports Server 2024*

## The Range of Electrified Aviation
Beyond commercial use, aircraft remain a vital resource for multiple departments for efficient operations. The most recognized is the role aviation plays in military systems, specifically in the Air Force, facilitating aerial inspections, delivering cargo, medical organs, and being used for training. For civilians, aircraft impact their every day, delivering packages, responding to disasters, and connecting lands to facilitate global transparency. Nevertheless, the integration of electric systems within aircraft also differs in severity and operation tactics.

As an introduction to electrification, electric power is guided towards powering all non-essential aircraft systems. These systems can include and are not limited to cabin systems, electricity, and communication radios. Within flight operations, this would represent less strain on the primary combustion engines, requiring them solely for propulsion rather than cabin power. On the tarmac, electric vehicles will replace gas-powered tugs to maneuver aircraft while contributing to the greener earth objective. These changes directly reduce the consumption of fossil fuels, operating on green power and limiting the release of toxic gases into the atmosphere.

Hybrid-electric is a term used for stronger electrification which introduces the integration of electric motors to produce synergistic interactions between all electric elements within an aircraft. These can be understood as electric motors operating alongside internal combustion engines for augmented power and regenerative capabilities that create a self-dependent system that charges the same power it uses. This integration can be directly translated to quieter travel for in-flight passengers as electric motors are responsible for maintaining cruising speeds rather than louder combustion engines.

The most efficient form of aircraft is referred to as truly electric or full electric. These aircraft rely solely on electric power and represent the cleanest form of aviation travel. The feasibility of these planes is a feat many engineers are approaching today, specifically identifying solutions to the battery carrying limitations due to their size and weight.

> **Table 1. Companies Manufacturing Electric Aircraft Prototypes**
> *Source: International Conference on Transportation and Development 2020*

## Propulsion and Operations
To achieve flight, aircraft energy consumption assimilates an inverse parabolic behavior where the most energy required is during departure and arrival. These high consumption periods release tons of toxic fumes as a by-product of burning fossil fuel within the internal combustion engine. Though at a smaller rate, aircraft continue to release these destructive gases throughout the entire flight. Traditionally, jets operate using turbofan engines which require large quantities of fuel to operate. Shifting towards hybrid technologies allows for the integration of electric motors, a homogenous process that enables them to work alongside turbofan engines rather than replace them. This advanced technology is a step closer to achieving future fully electric aircraft and displays efforts to reduce carbon footprint.

The concept is as follows: during takeoff when the aircraft requires the most power, electric engines will provide a boost to the turbofan engine to reduce strain and operate with less fuel consumption. While the carrier is in flight, the turbofan engine will operate at its most optimal strength, allowing the aircraft to maintain altitude, while the electric motors are responsible for supplementary loads such as battery cooling, lights, and power steering (Electrification 2024). The result of this hybrid technology is minimized fuel expenses and lower maintenance costs as engines operate with less strain and more efficiency. A study conducted at the Massachusetts Institute of Technology discovered the proposed design successfully reduces nitrogen oxide emissions by 95%, a released chemical that results in approximately 16,000 premature deaths every year (Chu 2021).

> **Figure 2: Proposed Hybrid-Electric Design to Reduce Global Nitrogen Oxide by 95%**
> *Source: MIT Researchers 2021*

## Driving Forces
The electric aircraft market was estimated to be $8.8 billion in 2022 and is expected to reach $37.2 billion by 2030 (Mehra n.d.). The growing interest in aircraft electrification is primarily driven by economic, environmental, and societal factors. In a report to congressional committees, key stakeholders such as airports, aircraft manufacturers, electrical utilities and air traffic management organizations voiced their interest in transitioning toward electrified air travel (USGAO 2022). Together they identified implementation barriers to better understand the challenges carried by this emerging industry. In NASA's most recent Regional Air Mobility report they identified the lack of recognition and attention to regional airports, highlighting how a breakthrough in electric propulsion systems would revolutionize local airports (Antcliff 2021).

The concept builds on the idea that electrified aircraft will be able to travel with more efficiency and a smaller carbon footprint while still maintaining profitable margins for airlines. These shifts will allow for the relocation of funds towards underutilized local airports to meet infrastructure requirements and better expand goals of renewable energy generation. Thus, the factors driving the electrification of aircraft are the following:

* **Reduced Emissions:** Emission reductions are one of the primary driving forces persuading airlines to shift towards cleaner travel. A report analyzing aircraft pollution concluded that the adaptation of hybrid-powered vehicles will allow the United States to achieve an 80% reduction of greenhouse gases and petroleum use by 2050 (Zhang 2024). The proposed integration of hybrid-electric aircraft success prevails largely in short-distance flights, previously regarded as the most energy inefficient, by allowing for cleaner and self-sufficient travel through regenerative braking.
* **Noise Reduction:** A large factor limiting the expansion of airports throughout the country is noise pollution caused by aircraft during takeoff and landing. Modern combustion engines pollute the air with toxic fumes and loud exhaust notes that bother both civilian homes surrounding airports and passengers within the aircraft. A study on noise emissions compared the interior cabin noise of a traditional fossil fuel aircraft to carry the same decibel weight as a lawn mower (Zhang 2024). It is estimated that the transition to fully electric propulsion could reduce aircraft noise by roughly 85% (White 2020).
* **Lower Costs:** From an economic standpoint, incorporating electricity into aircraft represents a profitable investment with a guaranteed return. Ampaire, an American aircraft manufacturer startup claims its hybrid-electric propulsion technology lowers fuel consumption by 90%, aircraft maintenance by 50%, and noise pollution by 60% (Ampaire 2025). The regenerative capabilities of electric motors allow for aircraft to fly more frequently without prolonged charging periods. Digitizing aircraft systems also facilitate the identification of issues the carrier might experience and allows for scheduled maintenance service to keep the aircraft functional.
* **Increased Accessibility:** The development of hybrid-electric aircraft introduces air travel as a clean method of transportation that is environmentally conscious and feasible for short distances. As urban cities expand and human population numbers reach an all-time high, current transportation infrastructures become inflexible and stationary; the result is rising city congestion and traffic jams (Beebe 2018). The solution to this inevitability is the introduction of air taxis that operate on clean energy. The switch will promote local travel and allow for urban architecture to adjust to a more efficient form of transportation.
* **Economic Development:** A Washington State study supports the shift to hybrid-electric aircraft by emphasizing the opportunity to repurpose neglected local airports and re-open shops that were previously vacated due to a lack of consumers (WSDOT 2020). The shift also introduces the opportunity for innovation, contradicting traditional forms of travel and taking steps toward a hybrid future.

## Hybrid-Electric Adoption
To effectively introduce hybrid technology as a reliable replacement to traditional combustion engines, mock trials, and aircraft efficiency must be appropriately measured. To do so, electric aircraft will be introduced into private sectors such as pilot training and private aviation. This controlled environment enables researchers to test hybrid behavior against traditional earth elements to appropriately determine it as a viable option for commercial travel. Modern attempts to test this technology have begun incorporating it into an existing fleet of over 200 thousand aircraft (Schwab 2021).

The Pipistrel's Alpha Electro is a perfect example of a market-ready aircraft that has received the European Union Aviation Safety Agency certification. Operating with a 60-kW motor and a 21-kWh battery, the Alpha Electro can effectively travel for nearly 160 kilometers or roughly an hour of flight time (Walków 2019). The near-term goal of adopting this technology is to be able to seamlessly introduce it into current air travel. This would recommend that aircraft travel shorter distances and carry smaller passenger amounts to minimize risks and ensure reliability.

Following this adoption, a transition will be made toward implementing an air taxi system that departs vertically rather than horizontally. This concept proposes fast travel time for short distances with disregard to road congestion. UberAir and Dubai Taxi (see Table 1) are some of the few competitors actively taking steps towards reliably integrating this technology. United Airlines has taken a similar approach, pushing for electrified air freight carriers that allow for enhanced mobility through densely populated areas (United 2021). The goal of this is to enhance production efficiency and utilize electric aircraft as a tool to promote their services.

## Conclusion
Electrified air travel will revolutionize transportation and will have everlasting impacts on how humans move. Nevertheless, prolonged research and development are undoubtedly still necessary to address the current barriers hindering the implementation of hybrid technology. High-capacity batteries for starters are a largely complex aspect that are fundamental for electric transportation yet carry multiple intricacies by design. Weight and density are a main concern; aircraft engineers must properly identify carrying capacities to reduce gravitational forces pulling on the aircraft, directly making the aircraft heavier and requiring more power.

The technologies required to charge these systems must also be explored as different applications require different power ratings and speeds; a move that pushes for innovating updated charging methods within international airports. Electrical wiring must be designed and carefully positioned to minimize interference with critical systems. New methods of maintenance must be taught and practiced to respond to wear and tear properly. Though universal standards are yet to be decided, it is well understood that their role in future implementations will be vital. The technology is now available, and it is only through its utilization that it can be explored further to soon achieve fully electric skies.

---

## References

* **Antcliff, K.** (2021). Regional Air Mobility – SACD. NASA. https://sacd.larc.nasa.gov/ram/
* **Beebe, A. J. B.** (2018). "Electric Flight Will Transform Our Cities for the Better, and It Will Happen Sooner Than You Think."
* **Downing, S.** (2019) 6 Electric Aviation Companies to Watch. https://www.greenbiz.com/article/6-electric-aviation-companies-watch
* **Electrification, C.** (2024). Comparing Electric, hybrid, and hydrogen-powered flight. Carpenter Electrification. https://www.carpenterelectrification.com/blog/comparing-electric-hybridhydrogen#:~:text=The%20combustion%20engine%20provides%20primary,power%20during%20takeoff%20and%20climbing.
* **Hyde, D.** (2024). Aviation: Benefits beyond borders global report. https://aviationbenefits.org/downloads/aviation-benefits-beyond-borders-2020/
* **Ingram, J.** (2023). How the airline industry is Tackling Climate Change. Defiance ETF. https://www.defianceetfs.com/how-the-airline-industry-is-tackling-climate-change/
* **Krause, H.** (2022). GAO-22-105020 Highlights, Advanced Air Mobility. Stakeholders Identified Issues to Address for 'Advanced Air Mobility. https://www.gao.gov/assets/gao-22-105020-highlights.pdf
* **Mehra, A.** (n.d.). Electric Aircraft Industry. Market Research Firm. https://www.marketsandmarkets.com/PressReleases/electric-aircraft.asp
* **Moua, L.** (2020) Critical Review of Advancements and Challenges of All-Electric Aviation doi:10.1061/9780784483138.005
* **Overton, J.** (2022). Issue brief: The growth in greenhouse gas emissions from Commercial Aviation EESI. https://www.eesi.org/papers/view/fact-sheet-the-growth-in-greenhouse-gasemissions-from-commercial-aviation
* **Schwab, A.** (2021). Electrification of Aircraft: Challenges, Barriers, and Potential Impacts. National Renewable Energy Laboratory (NREL). https://www.nrel.gov/docs/fy22osti/80220.pdf
* **Selkirk, D.** (2020). "Is This the Start of an Aviation Revolution? BBC. February 11, 2020. https://www.bbc.com/future/article/20200211-the-electric-plane-leading-a-revolution
* **United.** (2021). "United Adding Supersonic Speeds with New Agreement to Buy Aircraft from Boom Supersonic." United. June 3, 2021. https://hub.united.com/2021-06-03-united-addingsupersonic-speeds-with-new-agreement-to-buy-aircraft-from-boom-supersonic-2653216403.html
* **Walków, Marcin, and Qayyah Moynihan.** (2019). "This Electric Plane Takes Just One Hour to Charge and Can Travel 160 Kilometers for Just $5." Business Insider (June 19, 2019). https://www.businessinsider.com/electric-plane-charges-in-hour-can-cover-160km-2019-6/.
* **White, T.** (2020). Hybrid-electric propulsion--a great start to reducing aviation's carbon footprint. Collins Aerospace. https://www.collinsaerospace.com/news/stories/2020/03/whitehybrid-electric-propulsion-great-start-reducing-aviation-carbon-footprint
* **Windhorst, R.** (2024). NASA Technical Reports Server (NTRS). NASA. https://ntrs.nasa.gov/
* **Andrew Beebe, J. B.** (2018). "Electric Flight Will Transform Our Cities for the Better, and It Will Happen Sooner Than You Think."
* **WSDOT.** (2019). Electric Aircraft Working Group Report. June 2019. WSDOT Aviation Division. https://wsdot.wa.gov/sites/default/files/2019/07/15/ElectricAircraftWorkingGroupReportJune2019.pdf
* **Zhang, Hans & Harris, Joy.** (2024). Exploring the Technology Needed to Build Electric Passenger Planes. Journal of Student Research. 13. 10.47611/jsrhs.v13i1.6196.`,
  },
  {
    id: 'urban-maglev',
    title: "Urban Integration of Shanghai's Maglev Technology",
    heroImage: '/research/maglev/maglev-inforgraphic.jpeg',
    body: `# Study on the Urban Integration of Shanghai's Maglev Technology
**By Jossue Sarango**

## Abstract
As the first commercially operated train to incorporate electromagnetic suspension, it is essential to analyze how the Shanghai maglev train has implemented itself into the city of Shanghai. This research analyzes the efficiency of maglev technology and its consistency in successfully operating at a commercial level. It analyzes the urban setting of Shanghai, and the impact electromagnets have had on the landscape. Deformation and environmental vibration are linked to maglev technology and its severity is analyzed. The reversibility of these adverse effects is studied, and methods of monitoring are proposed. This study aims to identify the replicability of maglev technology in other urban cities across the world.

**Index Terms:** Intercity and urban application; Ground subsidence; Shanghai maglev; Environmental vibration; Maintenance protocols; Electromagnetic suspension.

## I. Introduction
The Shanghai Maglev Train, otherwise known as the Shanghai Transrapid, is the first, the fastest, and the only commercially operated magnetically levitated train in the world. Inaugurated on December 31, 2002, the Shanghai Maglev Train resides in the centermost city of Shanghai, China. It connects two highly transported destinations, the Longyang Road Station and the Pudong International Airport Station for a continued operation of 15 hours/day, 7 days/week. The Shanghai Maglev currently connects thirty kilometers, a distance traveled in just under eight minutes. These short times combined with an exceptional top operational velocity of 430km/h have brought international attention to the Shanghai Transrapid. Magnetic levitation, as the name suggests, operates through magnetic attraction and propulsion forces. The laws of physics demonstrate that like forces pull towards each other and opposite forces push away from each other. The combination and configuration of these behaviors are shifted electronically to maintain the Shanghai Maglev always levitating over its tracks.

As maglev technology becomes widely recognized and innovators push towards recreating these train systems internationally, it is essential to analyze the successful integration of the Shanghai Maglev Train in an urban setting. This study will analyze the electromagnetic suspension which categorizes the Shanghai Maglev to determine the adverse effects magnetic fields and their nature to vibrate have on building infrastructures. The longevity of maglev trains will be analyzed, focusing specifically on their impact on geological settlement. It is essential to recognize these concerns to implement a method of maintenance that can be universally applied and translated to similar technologies globally. These discoveries will demonstrate the components necessary to expand or replicate maglev train lines across other urban areas.

## II. Urban Integration
The 2002 implementation of the Shanghai Maglev Train line signified a revolutionary advancement in transportation technologies that changed the way people understood travel. A research study analyzing traffic congestion and environmental conservation in Shanghai, China, discovers that "the maglev system has the advantages of lower noise and vibration, better curve negotiation and grade abilities, higher reliability, and lower maintenance costs" (Han, 2024, p. 1). Compared to traditional rail-wheel transportation, the electromagnetic suspension that characterizes the Shanghai Transrapid allows the carriers to operate without touching any surfaces, reducing friction forces and subsequently improving comfortability for its passengers.

With a TR-08-designed train carrier divided into five sub-sections, the Shanghai Transrapid has a cumulative carrying capacity of roughly five hundred passengers. Luguang's (2006) research focused on quantifying the operational efficiency of the Shanghai Maglev discovers that "till the end of May 2005, [Shanghai Maglev] operated safely and reliably for 883 days, [traveling a cumulative distance of] 1.56M km and carried 3.51M passengers" (p. 1139). The data collected underscores the operational efficiency of the maglev train and its ability to respond appropriately to the harsh demands of urban transportation. Throughout the years, the Shanghai Maglev has developed a proven track record that supports its reliability and successful integration in an urban setting. The operational success of the Shanghai Maglev is a direct testament to modern technology integrating to improve everyday life.

In a dimensional analysis of the size and operational abilities of the Shanghai Maglev, Luguang (2006) identifies that "The small bending radius (50–70 m) and high climbing capability (7–10%) make the maglev especially suitable for areas with small space and high roughness" (p. 1141). The design of the Shanghai Maglev appropriately adapts to urban settings, commonly characterized by their small spaces and intricate landscapes. These unique characteristics of being able to climb steep landscapes and bend tight corners directly address common transportation issues identified by urban cities by allowing maglev trains to operate around already existing infrastructure, reducing further modifications. These features combined push towards an understanding that maglev trains can thrive in urban cities and engage individuals more than traditional trains.

## III. EMS Vibrations
Electromagnetic suspension operates by manipulating the attractive force between iron-core electromagnets and ferromagnetic rails. The nature of this technology relies on continuously active suspension force adjustment, a shifting movement that creates consistent vibrations. In an environmental research article analyzing the impact of shifting magnetic forces, Han (2006) discovers that "during the running of a maglev train, the vehicle and railway track constantly vibrate and propagate the vibration to the surrounding environment…[causing] serviceability problems [and] even vibration pollution" (p. 2). These discoveries point towards the larger problem of extensive vibrations that extend far beyond just the Shanghai Maglev train line. This is especially concerning considering the large population of 24.87 million residents and the large commercial and residential areas that surround the maglev train line.

To quantify the magnitude of vibrations emitted by the Shanghai Maglev, Han (2006) determines "the irregularity… between adjacent girders has significant effects on the guideway structure vibration response, and the impact when maglev trains pass from girder to girder can reach up to 20 m/s^2" (p. 15). The vibrations emitted by the Shanghai Maglev, despite being below the human threshold, still pose a threat to the durability and extended integrity of the maglev train line. These characteristics hinder the replicability of maglev lines in other urban settings and pave the way for preventative practices that must be instilled to counteract these challenges. During the construction of the Metro Shield Tunnel undercrossing the Shanghai Maglev protected area, researchers proposed, "deformation monitoring should continue… [because] dynamic load [and vibration] can exist during the engineering operation period" (Wang, 2018, p. 1097). These preventative practices of monitoring deformation directly address the challenges presented by maglev technology. It is essential to recognize these adversities in future maglev applications to ensure the vibrational movements emitted do not deteriorate the maglev train's efficiency.

## IV. Geological Settlement
Shanghai's widely recognized fragile geological environment and poor engineering properties pose concerns about the impact vibrations have on ground subsidence. In a study analyzing ground deformation near the Maglev train line, researchers identified "vibration load caused by the operation of Maglev train… induced the dissipation of excess pore water pressure and contributed to the consolidation of surrounding soil" (Cui, 2015, p. 1777). The thick and poor-behaving soil that surrounds the Shanghai Maglev and the Yangtze River Delta displays characteristics of settlement growing larger along the magnetic suspension line. These unique challenges specific to Shanghai's geological landscape raise concern regarding just how universal maglev may be.

To illustrate the geological complications researchers determined, "the operation of Maglev train can affect the stability of soil layers and increase land subsidence… [preventative] special measures must be made" (Cui, 2015, p.1778). Settlements negatively impact the structure of these intricate projects by increasing their internal stress, hindering performance, and reducing service life. In fact, soil properties directly impact the resilience of maglev infrastructures. Researchers discovered this phenomenon during a shield tunneling project near the Maglev train line's protected area describing, "the soil… produced different degrees of deformation, [leading] to the deformation of the Maglev pile foundation, cap, and column" (Wang, 2018, p. 1095). These findings suggest that the geological characteristics under which maglev train lines are established play a critical role in the efficiency and longevity of these projects. It becomes essential to consider these factors when thinking of the possibility of expanding the train line or further introducing a similar technology around the world.

## V. Regulations and Maintenance
Given the intricate nature of electromagnetic suspension, it is essential to support the technology with equally advanced methods of monitoring and maintenance. To better understand how the Shanghai Maglev has persevered despite vibrational and geological challenges, researchers analyzed the current existing maintenance management core system; they discovered, "each subsystem… can adapt to the different characteristics of each subsystem, …can target special characteristics, …[and] avoids the mutual influence of diagnosis system" (Cui, 2015, p. 1934). These discoveries illustrate the efficiency of operating a management line that is run individually alongside the Shanghai Maglev. The efficiency of this management line is demonstrated through more than two decades of successful operation.

Further innovations introduce new methods of monitoring settlement which can be incorporated into maglev monitoring and can be universally translated to other maglev applications. During the construction of the Shanghai Metro Line 13 a new method of measuring settlement deformation was introduced which involved an observation ring being buried and an automatic monitoring system capturing automatically sampling intervals every 2 minutes (Wang, 2018, p. 1100). The introduction to comprehensive monitoring methods captures the importance of regulating external factors that also influence the integrity of maglev train lines. The incorporation of external analysis can work with existing monitoring systems to better prevent extraordinary occurrences.

In a study on the current methods of regulating the Shanghai Maglev, Cui (2015) finds that "Due that the user interface of the original system is not friendly enough to provide graphic operation, data entry and query of website forms, …the system is not convenient for operation and maintenance staff" (p. 1940). Given the limitations of the current method of monitoring electromagnetic suspension, it is essential to recognize that these maintenance practices may improve by merging the physical and digital worlds. By logging data and creating a digital system that can facilitate the analysis of specific components, maglev trains can be operated more efficiently, and the structural integrity of their platforms can remain intact.

## VI. Conclusion
The development of the Shanghai Maglev is a direct response to modern transportation challenges, inspiring innovation for advancements in urban transit systems. In analyzing the unique properties that give the Shanghai Maglev the ability to levitate and reach high velocities, multiple challenges regarding the viability of maglev technology were discovered. The challenges of extensive vibrations across nearby infrastructures were interpreted to understand the external implications large magnetic fields may have. The impact of these vibrations was also discovered to directly impact geological settings, effecting the settlement and hindering the infrastructures for the train lines.

Through this discovery though, methods of monitoring adverse changes were proposed to counteract possible negative effects produced by maglev technology. Together they work to facilitate the integration of maglev technology in other urban areas; allowing for a better understanding of the underlying factors that characterize maglev and create transparency between a new technology that is not widely recognized. Nonetheless, the success of the Shanghai Maglev represents a step-forward in discovering newer ways of moving around. It's unique design and ability to maneuver around complex urban frameworks make it a great addition to dense urban cities like Shanghai. As cities continue to pursue faster methods of transportation, the accomplishments Shanghai Maglev has made thus far should serve to inspire.

---

## References

* **Chen, J., Gui, W., Cui, W., Tang, D., & Kong, L.** (2015). Analysis of Maintenance Management Core System on the Shanghai Maglev Demonstration Line. In CICTP 2015 (pp. 1931–1941). https://doi.org/10.1061/9780784479292.180
* **Cui, Z., & Yuan, Q.** (2015). Study on the settlement caused by the Maglev train. Natural Hazards, 75(2), 1767-1778. https://doi.org/10.1007/s11069-014-1396-9
* **Han, Z., Zeng, G., & Ye, F.** (2024). Research on Environmental Vibration Induced by High-Speed Maglev Transportation. Applied Sciences, 14(1), 413-. https://doi.org/10.3390/app14010413
* **Luguang, Y.** (2006). Progress of the Maglev Transportation in China. In IEEE Transactions on Applied Superconductivity (Vol. 16, Issue 2, pp. 1138–1141). Institute of Electrical and Electronics Engineers (IEEE). https://doi.org/10.1109/tasc.2006.871345
* **Wang, G. Q., Hu, S. T., Ye, F., Zeng, G. F., & Lv, Q.** (2018). Comprehensive Technical Monitoring for Maglev Structure during Metro Shield Tunnel Undercrossing in Shanghai Maglev Protected Area. CICTP 2018: Intelligence, Connectivity, and Mobility - Proceedings of the 18th COTA International Conference of Transportation Professionals, 1095–1101. https://doi.org/10.1061/9780784481523.108`,
  },
];
